export const FETCHING_DATA = "FETCHING_DATA"
export const FETCH_DONE = "FETCH_DONE"
export const FETCH_ERROR = "FETCH_ERROR"

export const FETCH_TECH_SUCCESS = "FETCH_TECH_SUCCESS"
export const FETCH_TECH_ERROR = "FETCH_TECH_ERROR"
export const FETCH_TECH = "FETCH_TECH"

export const FETCH_BITCOIN_SUCCESS  = "FETCH_BITCOIN_SUCCESS"
export const FETCH_BITCOIN_ERROR  = "FETCH_BITCOIN_ERROR"
export const FETCH_BITCOIN  = "FETCH_BITCOIN"

export const FETCH_APPLE_SUCCESS  = "FETCH_APPLE_SUCCESS"
export const FETCH_APPLE_ERROR  = "FETCH_APPLE_ERROR"
export const FETCH_APPLE = "FETCH_APPLE"



